# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoRNFlutter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DemoRNFlutter


end

flutter_application_path = '../demo_flutter'
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
